POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJpZmYyQGdtYWlsLmNvbSIsImV4cCI6MTc1NTQ1Mjg2NSwidXNlcklkIjoyfQ.Jx6w3II_H3HPm1rdSdQ_v0Aac2opfTWnomDwjcfgi5c

{
    "name": "test event for test update",
    "description": "A test event2",
    "location": "a test location",
    "dateTime": "2025-01-01T15:22:00.000Z"
}