POST http://localhost:8080/events
content-type: application/json

{
    "name": "test event",
    "description": "A test event",
    "location": "a test location",
    "dateTime": "2025-01-01T15:22:00.000Z"
}