
PUT http://localhost:8080/events/8
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJpZmYzQGdtYWlsLmNvbSIsImV4cCI6MTc1NTQ1MTEzMiwidXNlcklkIjoyfQ.MAZs2Yr2eRJlRvPyIycyf18VV1dv5fNjZzxFRx5fTvY

{
  "name": "test event",
  "description": "A test event update",
  "location": "a test location",
  "dateTime": "2025-02-01T15:22:00Z"
}